- hosts: all
  tasks:
  - command: date
    register: x
  - service:
      name: "httpd"
      state: started
    register: y
  - debug:
      msg: "Hi resting"
    when: x.rc != 0
  - debug:
      var: y
  - debug:
      msg: "final"
    when: x.rc == 0 or y.failed == false
 
