- hosts: all
  vars_prompt: 
       - name: dvd_dir
         private: no
         prompt: "Enter the Dvd mount Point "
  tasks:
  - file:
     state: directory 
     path: "{{ dvd_dir }}"
  - mount:
     src: "/dev/sr0"
     path: " {{ dvd_dir }}"
     state: mounted
     fstype: "iso9660"
  - yum_repository:
         baseurl: "{{ dvd_dir }}/AppStream"
         name: "mydvd1"
         description: "Myyum dvd1 for packages"
         gpgcheck: no
  - yum_repository:
          baseurl: "{{ dvd_dir }}/BaseOS"
          name: "mydvd2"
          description: "Myyum dvd2 for packages"
          gpgcheck: no
  - package:
         name: "httpd"
         state: present
  - file:
      state: directory
      path: "/var/www/janu"
  - copy:
      dest: "/etc/httpd/conf.d/lw.conf"
      src: "lw.conf"
  - copy:
       dest: "/var/www/janu/index.html"
       content: "This is my newwww web site\n"
  - service:
        name: "httpd"
        state: restarted
        enabled: yes
  - firewalld:
        port: "8080/tcp"
        state: enabled
        permanent: yes
        immediate: yes
